# このファイルはRustプロジェクトのコード整形ツールrustfmtの設定ファイルです。
# 各設定値はコードのフォーマットスタイルやインポートの扱い、コメントの整形方法などを制御します。
# [Rustfmt](https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=)

style_edition = "2024"                # 使用するRustのエディションに合わせたスタイルを適用します。
use_small_heuristics = "Max"          # 小規模なコードブロックの整形に最大限のヒューリスティックを適用します。
group_imports = "StdExternalCrate"    # インポートを標準・外部・クレートごとにグループ化します。
imports_granularity = "Module"        # インポートの粒度をモジュール単位に設定します。
format_code_in_doc_comments = true    # ドキュメントコメント内のコードも整形対象にします。
newline_style = "Unix"                # 改行コードをUnixスタイル（LF）に統一します。
use_field_init_shorthand = true       # 構造体初期化時にフィールド短縮記法を使用します。
