# このファイルはCargoのリリースビルド時の設定を記述しています。
# 特にWindows(MSVC)環境でのリンク方法や、ビルド時の標準ライブラリ・パニック処理の挙動を制御します。

# The following is not used by default via .cargo/config.toml,
# because `build-std-features` cannot be keyed by profile.
# This breaks the bench profile which doesn't support panic=abort.
# See: https://github.com/rust-lang/cargo/issues/11214
# See: https://github.com/rust-lang/cargo/issues/13894

# [target.'cfg(all(target_os = "windows", target_env = "msvc"))'] セクション:
# WindowsのMSVC環境でビルドする際のrustcフラグを指定します。
# - "-Ctarget-feature=+crt-static": Cランタイムを静的リンクします。
# - "-Clink-args=/DEFAULTLIB:ucrt.lib": ucrtbase.dllを動的リンクします。
# - "-Clink-args=/NODEFAULTLIB:vcruntime.lib" など: vcruntime140.dllやmsvcrt.dll等の不要なDLLとのリンクを回避します。
# これにより、vcruntime140.dllが不要な環境でも実行可能なバイナリを生成します。
[target.'cfg(all(target_os = "windows", target_env = "msvc"))']
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Clink-args=/DEFAULTLIB:ucrt.lib",
    "-Clink-args=/NODEFAULTLIB:vcruntime.lib",
    "-Clink-args=/NODEFAULTLIB:msvcrt.lib",
    "-Clink-args=/NODEFAULTLIB:libucrt.lib",
]

# [unstable] セクション:
# ビルド時に標準ライブラリ(std)とパニック時の動作(panic_abort)を含めてビルドします。
# - build-std = ["std", "panic_abort"]: 標準ライブラリとパニック時即時abortの機能を有効化します。
# - build-std-features = ["panic_immediate_abort"]: パニック時に即座にabortすることでバイナリサイズを削減します。
# これにより、パニック時のバックトレースコードを除外し、バイナリサイズを大幅に削減します。
[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
